=head1 NAME

Bro::Log::Parse - Object-oriented Perl interface for parsing Bro log files

=head1 SYNOPSIS

  use Bro::Log::Parse;
  
  my $parse = Bro::Log::Parse->new('/path/to/logfile');
  while ( $fields = $parse->getLine() ) {
    print $fields->{ts}."\n";
  }

=head1 ABSTRACT

Perl interface for parsing Bro logfiles

=head1 DESCRIPTION

This library provides an easy and convenient way to parse the log files generated
by the L<Bro Network Monitoring System|http://www.bro.org>.

=head1 FUNCTIONS

=head2 new(constructor)

The base constructor for Bro::Log::Parse classes. It takes a mandatory parameter containing
the path to the logfile as an adrument and returns the new object. If no file is specified,
input will be read from <>.

If the file pointed to does not exist or cannot be opened, a fatal error is raised.

=head2 getLine()

Read the the line of the input and return the parsed data as a hash. Returns
undef when on EOF.

=head1 AUTHOR
Johanna Amann, E<lt>johanna@icir.orgE<gt>

=head1 COPYRIGHT AND LICENSE
Copyright 2014 by Johanna Amann
This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

